src/Entity/Article.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\Table(name="articles")
 * @ORM\HasLifecycleCallbacks()
 */
class Article
{
    const STATUS_DRAFT = 'Draft';
    const STATUS_PUBLISHED = 'Published';
    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     */
    private $author;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=false)
     */
    private $status;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $title;

    /**
     * @var string
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleImage", mappedBy="article")
     * @ORM\OrderBy({"id" = "ASC"})
     */
    private $images;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=false, options={"default": false})
     */
    private $removed;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $tempLink;

    /**
     * @var integer|null
     * @ORM\Column(type="integer", nullable=false, options={"default": 0})
     */
    private $commentsCount;

    /**
     * @var integer|null
     * @ORM\Column(type="integer", nullable=false, options={"default": 0})
     */
    private $viewsCount;

    /**
     * @var DateTime|null
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @var DateTime
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @var DateTime
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * Project constructor.
     */
    public function __construct()
    {
        $this->setCreatedAt(new DateTime('now'));
        $this->setRemoved(false);
        $this->setViewsCount(0);
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new DateTime('now'));
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return User
     */
    public function getAuthor(): User
    {
        return $this->author;
    }

    /**
     * @param User $author
     */
    public function setAuthor(User $author): void
    {
        $this->author = $author;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * @param string $text
     */
    public function setText(?string $text): void
    {
        $this->text = $text;
    }

    /**
     * @return bool
     */
    public function isRemoved(): bool
    {
        return $this->removed;
    }

    /**
     * @param bool $removed
     */
    public function setRemoved(bool $removed): void
    {
        $this->removed = $removed;
    }

    /**
     * @return DateTime
     */
    public function getCreatedAt(): DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param DateTime $createdAt
     */
    public function setCreatedAt(DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return DateTime
     */
    public function getUpdatedAt(): DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param DateTime $updatedAt
     */
    public function setUpdatedAt(DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function isDraft()
    {
        return self::STATUS_DRAFT === $this->getStatus();
    }

    public function isPublished()
    {
        return self::STATUS_PUBLISHED === $this->getStatus();
    }

    /**
     * @return Collection
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    /**
     * @param Collection $images
     */
    public function setImages(Collection $images): void
    {
        $this->images = $images;
    }

    /**
     * @return int
     */
    public function getCommentsCount(): int
    {
        return $this->commentsCount;
    }

    /**
     * @param int $commentsCount
     */
    public function setCommentsCount(int $commentsCount): void
    {
        $this->commentsCount = $commentsCount;
    }

    public function getShort(): string
    {
        preg_match("/^(.*)<cut \/>/uis", $this->text, $matches);
        if(isset($matches[1])) {
            return $matches[1];
        }
        return $this->text;
    }

    /**
     * @return DateTime
     */
    public function getPublishedAt(): ?DateTime
    {
        return $this->publishedAt;
    }

    /**
     * @param DateTime $publishedAt
     */
    public function setPublishedAt(?DateTime $publishedAt=null): void
    {
        $this->publishedAt = $publishedAt;
    }

    /**
     * @return string
     */
    public function getTempLink(): ?string
    {
        return $this->tempLink;
    }

    /**
     * @param string $tempLink
     */
    public function setTempLink(?string $tempLink): void
    {
        $this->tempLink = $tempLink;
    }

    /**
     * @return int|null
     */
    public function getViewsCount(): ?int
    {
        return $this->viewsCount;
    }

    /**
     * @param int|null $viewsCount
     */
    public function setViewsCount(?int $viewsCount): void
    {
        $this->viewsCount = $viewsCount;
    }
}

src/Form/Blog/ArticleType.php
<?php

namespace App\Form\Blog;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, ['label' => 'editor.title'])
            ->add('text', TextareaType::class, ['label' => 'editor.text']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Article::class,
        ));
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Entity\User;
use App\Entity\UserSubscriptions;
use App\Form\CommentType;
use App\Notifications\Notificator;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use App\Repository\UserSubscriptionsRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use FeedIo;
use Knp\Component\Pager\PaginatorInterface;
use Psr\Http\Message\ResponseInterface;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog/{page}", name="blog_list", defaults={"page": 1})
     *
     * @param ArticleRepository  $articleRepository
     * @param PaginatorInterface $paginator
     * @param int                $page
     *
     * @return Response
     */
    public function indexAction(
        ArticleRepository $articleRepository,
        PaginatorInterface $paginator,
        int $page = 1
    ) {
        $articles = $articleRepository->getPublishedQuery();

        $pagination = $paginator->paginate(
            $articles,
            $page
        );

        return $this->render('blog/list/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    /**
     * @Route("/blog/{article}/more", name="blog_more")
     *
     * @param Article $article
     * @param CommentRepository $commentRepository
     * @param UserSubscriptionsRepository $subscriptionsRepository
     * @param EntityManagerInterface $entityManager
     *
     * @return Response
     *
     * @throws NonUniqueResultException
     */
    public function moreAction(
        Article $article,
        CommentRepository $commentRepository,
        UserSubscriptionsRepository $subscriptionsRepository,
        EntityManagerInterface $entityManager
    )
    {
        /** @var User $user */
        $user = $this->getUser();

        $article->setViewsCount($article->getViewsCount() + 1);
        $entityManager->persist($article);
        $entityManager->flush();

        $isUserSubscribed = $user
            ? (bool) $subscriptionsRepository->getUserSubscribedToArticleComments($this->getUser(), $article)
            : false;

        if (Article::STATUS_PUBLISHED !== $article->getStatus()) {
            throw new NotFoundHttpException();
        }

        return $this->render('blog/more/index.html.twig', [
            'article' => $article,
            'commentForm' => $this->createForm(CommentType::class)->createView(),
            'comments' => $commentRepository->getForArticle($article),
            'isUserSubscribed' => $isUserSubscribed,
        ]);
    }

    /**
     * @Route("/blog/{tempId}/draft", name="blog_draft")
     *
     * @param string            $tempId
     * @param ArticleRepository $articleRepository
     *
     * @return Response
     */
    public function draftAction(string $tempId, ArticleRepository $articleRepository)
    {
        $article = $articleRepository->findOneBy(['tempLink' => $tempId]);
        if (null === $article) {
            throw new NotFoundHttpException();
        }

        return $this->render('blog/more/index.html.twig', [
            'article' => $article,
            'commentForm' => $this->createForm(CommentType::class)->createView(),
            'comments' => [],
            'isUserSubscribed' => false,
        ]);
    }

    /**
     * @Route("/blog/{article}/comment/submit", name="blog_add_comment")
     *
     * @param Request                $request
     * @param EntityManagerInterface $em
     * @param TranslatorInterface    $translator
     * @param Article                $article
     * @param Notificator            $notificator
     *
     * @return Response
     */
    public function submitComment(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        Article $article,
        Notificator $notificator
    ) {
        $user = $this->getUser();

        if (!$user) {
            throw new AccessDeniedException();
        }

        $form = $this->createForm(CommentType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment = $this->createComment($user, $form, $article, $em);
            $this->addFlash('add-comment-success', $translator->trans('comments.comment_successfully_added'));
            $notificator->newArticleComment($article, $comment);
        }

        return $this->redirectToRoute('blog_more', ['article' => $article->getId()]);
    }

    /**
     * @param User                   $user
     * @param FormInterface          $form
     * @param Article                $article
     * @param EntityManagerInterface $em
     *
     * @return Comment
     */
    private function createComment(User $user, FormInterface $form, Article $article, EntityManagerInterface $em): Comment
    {
        $comment = new Comment();
        $comment->setFrom($user);
        $comment->setEntity(Comment::ENTITY_ARTICLE);
        $comment->setToId($article->getId());
        $comment->setMessage($form->get('comment')->getData());
        $comment->setRemoved(false);
        $article->setCommentsCount($article->getCommentsCount() + 1);

        $em->persist($comment);
        $em->persist($article);
        $em->flush();

        return $comment;
    }

    /**
     * @Route("/blog/{article}/comments/subscribe", name="article_comment_subscription", methods={"POST"})
     *
     * @param Article                     $article
     * @param UserSubscriptionsRepository $subscriptionsRepository
     * @param EntityManagerInterface      $entityManager
     *
     * @return JsonResponse
     *
     * @throws NonUniqueResultException
     */
    public function commentsSubscribe(
        Article $article,
        UserSubscriptionsRepository $subscriptionsRepository,
        EntityManagerInterface $entityManager
    ) {
        $user = $this->getUser();

        if (!$user) {
            throw new AccessDeniedException();
        }

        $subscription = $subscriptionsRepository->getUserSubscribedToArticleComments($user, $article);
        if (null !== $subscription) {
            $entityManager->remove($subscription);
            $entityManager->flush();

            return new JsonResponse(['success' => true]);
        }

        $subscription = new UserSubscriptions();
        $subscription->setUser($user);
        $subscription->setEntityId($article->getId());
        $subscription->setEvent(UserSubscriptions::EVENT_NEW_COMMENT_TO_ARTICLE_ADDED);
        $entityManager->persist($subscription);
        $entityManager->flush();

        return new JsonResponse(['success' => true]);
    }

    /**
     * @Route("/blog/feed/rss", name="blog_rss", methods={"GET"})
     *
     * @param TranslatorInterface $translator
     * @param ArticleRepository   $articleRepository
     *
     * @return ResponseInterface
     *
     * @throws \Exception
     */
    public function rssAction(TranslatorInterface $translator, ArticleRepository $articleRepository)
    {
        $feedIo = FeedIo\Factory::create()->getFeedIo();
        $feed = new FeedIo\Feed();
        $feed->setTitle($translator->trans('blog.feed_title'));
        $articles = $articleRepository->getPublished();
        /** @var Article $article */
        foreach ($articles as $article) {
            $item = new FeedIo\Feed\Item();
            $item->setTitle($article->getTitle());
            $item->setDescription($article->getShort());
            $item->setLastModified($article->getUpdatedAt());
            $item->setPublicId($article->getId());
            $item->setLink($this->generateUrl(
                'blog_more',
                ['article' => $article->getId()],
                UrlGeneratorInterface::ABSOLUTE_URL
            ));
            $feed->add($item);
        }
        $feed->setLastModified(new DateTime());

        $feedResponse = $feedIo->getPsrResponse($feed, 'rss');

        return new Response($feedResponse->getBody()->getContents(), Response::HTTP_OK, $feedResponse->getHeaders());
    }
}

templates/blog/more/index.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ article.title }} {% endblock %}
{% block meta_description %} {{ article.short | striptags }} {% endblock %}
{% block body %}
    <div class ="container">

        {% for message in app.flashes('add-comment-success') %}
            <div class="success-message margin-top-20">
                {{ message | raw}}
            </div>
        {% endfor %}

                <article class="post blog-post">
                    <div class="entry-content">
                        <div class="entry-meta">
                            <div class="info">
                                <div class="meta margin-top-1">
                                    {% if article.publishedAt %}
                                    <span class="date"><i class="mn-icon-1130"></i>{{ article.publishedAt|localizeddate('short', 'none') }}</span>
                                    {% else %}
                                    <span class="date"><i class="mn-icon-1130"></i>{{ article.createdAt|localizeddate('short', 'none') }}</span>
                                    {% endif %}
                                </div>
                                <div class="row"><div class="col-sm-12"><h1 class="entry-title">{{ article.title }}</h1></div></div>
                            </div>
                        </div>
                        <div class="info-bottom">
                            <div class="info-description blog-text">{{ markdown (article.text) | raw }}</div>
                        </div>
                        <div class="row padding-top-15">
                            <div class="offset-md-3 col-md-9">
                                <h2>{{ 'blog.share' | trans }}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="offset-md-3 col-md-2">
                                <a target="href" href="https://www.facebook.com/sharer/sharer.php?u={{ url('blog_more', {"article": article.id}) }}" class="fb-share-button social-share-buttons"><i class="fab fa-facebook"></i></a>
                            </div>
                            <div class="col-md-2">
                                <a target="href" href="http://vkontakte.ru/share.php?url={{ url('blog_more', {"article": article.id}) }}" class="social-share-buttons"><i class="fab fa-vk"></i></a>
                            </div>
                            <div class="col-md-2">
                                <a class="social-share-buttons"
                                   href="https://twitter.com/intent/tweet?text={{ article.title }}&url={{ url('blog_more', {"article": article.id}) }}&hashtags=teamstarter,startup"
                                   data-size="large"
                                   target="_blank"
                                >
                                    <i class="fab fa-twitter"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </article>

                {% include 'blog/common/comment_list.html.twig' %}
                {% if app.user %}
                    {% include 'blog/common/comment_form.html.twig' %}
                    {% if app.user %}
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2 form-section">
                                <div class="row"> <div class="col-md-12 form-group text-center">
                                        <label class="form-check-label hint"><input type="checkbox" id="article-comments-subscriptions" {% if isUserSubscribed %} checked="checked" {% endif %}> {{ 'comments.comments_subscription' | trans }}</label>
                                </div></div>
                            </div>
                        </div>
                    {% endif %}
                {% else %}
                    <div class="row">
                        <div class="col-md-12 form-section margin-top-20 margin-bottom-20">
                            <div class="row"> <div class="col-md-12 form-group text-center">
                                    {{ 'comments.comment_form_authorise_message' | trans ({"%link%": "/login"}) | raw }}
                                </div></div>
                        </div>
                    </div>
                {% endif %}

    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $(function () {
            $("#article-comments-subscriptions").click(function() {
                $("#article-comments-subscriptions").attr('disabled', 'disabled');
                $.ajax({
                    type: "POST",
                    url: "{{ path('article_comment_subscription', {"article": article.id}) }}",
                    data: '',
                    success: function() {
                        $("#article-comments-subscriptions").removeAttr('disabled');
                    }
                });
            });
        })
    </script>
{% endblock %}

{% block meta %}
    <meta property="og:url"                content="{{ url('blog_more', {"article": article.id}) }}" />
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="{{ article.title }}" />
    <meta property="og:description"        content="{{ article.short | striptags }}" />
    <meta property="fb:app_id" content="524207097955709" />
    {% if article.images[0] is defined %}
    <meta property="og:image"              content="{{ app.request.getSchemeAndHttpHost() ~  article.images[0] }}" />
    {% endif %}
{% endblock %}